### PR TITLE
Add replications service

### LINKED ISSUE #39: Add support for configuring replications
# Below are required fields for qualifying your issue to our support team

## Subject of the issue

- [ ] Add support for configuring replications

## Your environment

- [ ] Artifactory 6.15.0

## Expected behavior

- [ ] CRUD support for replications
- [ ] Either a separate replications service or attach get/set methods to local and remote repository structs for push and pull replications, respectively. 
- [ ] [Artifactory+REST+API#ArtifactoryRESTAPI-GetRepositoryReplicationConfiguration](http://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-GetRepositoryReplicationConfiguration)
- [ ] [Artifactory+REST+API#ArtifactoryRESTAPI-SetRepositoryReplicationConfiguration](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-SetRepositoryReplicationConfiguration)
- [ ] [Artifactory+REST+API#ArtifactoryRESTAPI-UpdateRepositoryReplicationConfiguration](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateRepositoryReplicationConfiguration)
- [ ] [Artifactory+REST+API#ArtifactoryRESTAPI-DeleteRepositoryReplicationConfiguration](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-DeleteRepositoryReplicationConfiguration)
- [ ] [Artifactory+REST+API#ArtifactoryRESTAPI-CreateLocalMulti-pushReplication](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-CreateLocalMulti-pushReplication)
- [ ] [Artifactory+REST+API#ArtifactoryRESTAPI-UpdateLocalMulti-pushReplication](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-UpdateLocalMulti-pushReplication)
- [ ] [Artifactory+REST+API#ArtifactoryRESTAPI-DeleteLocalMulti-pushReplication](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-DeleteLocalMulti-pushReplication)
- [ ] [Artifactory+REST+API#ArtifactoryRESTAPI-CreateorReplaceLocalMulti-pushReplication](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-CreateorReplaceLocalMulti-pushReplication)
- [ ] [Replication+Configuration+JSON](https://www.jfrog.com/confluence/display/RTF/Replication+Configuration+JSON)

## Actual behavior

N/A

## Steps to Reproduce

N/A

### PR DESCRIPTION
**Pull request by joeh90**
Closes #39.

Adds the following functionality:

- create/update/delete single local and remote replications
- create/update/delete multi-push replication

Things to note/for discussion:

- Artifactory REST API Get method returns a JSON array for a local replication or a JSON object for a remote replication. This implementation returns a slice for both in order to maintain consistency.
- Undocumented replications REST API endpoint, which I've added a GetAll() method for.

### CODE REVIEW

**Comment by joeh90** [comment]
Sorry about the mess...

**Comment by JordanSussman** [comment]
The initial code review looks fine besides the minor typo but I'd like to some further testing tomorrow when I'm in the office. 

Thanks for submitting this @joeh90.

**Comment by joeh90** [comment]
> The initial code review looks fine besides the minor typo but I'd like to do some further testing tomorrow when I'm in the office.
> 
> Thanks for submitting this @joeh90.

Ah, good spot - my bad!

Great, thanks @JordanSussman.

**Comment by jbrockopp** [comment]
🎉 @joeh90 thanks for your contribution! 🎉

**Comment by JordanSussman** [comment]
I'll try and test this against some Artifactory instances tomorrow.

**Comment by JordanSussman** [comment]
Any input @jbrockopp?

**Pull request merged**
